apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshope
  namespace: argocd
spec:
  project: default
  destination:
    namespace: eshope
    server: https://kubernetes.default.svc
  source:
    path: K8S
    repoURL: https://github.com/Sreev10/GKE-Eshop.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - ApplyOutOfSyncOnly=true    