apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: eshope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eshop/api:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD  
          resources:
              requests:
                memory: "128Mi"
                cpu: "100m" 
              limits:
                memory: "512Mi"
                cpu: "500m"
          
      