apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eshope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: eshop/frontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: API_URL  
          resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"